class CFG:
    EXCEL_PATH = './data/附件.xlsx'
    SHEET_NAME = '男胎检测数据'
    Q1PicPath = './output/Q1/'
    Q2PicPath = './output/Q2/'
    Q3PicPath = './output/Q3/'
    COL_ID = '孕妇代码'
    COL_BMI = '孕妇BMI'
    MAX_BMI_POINTS = 250
    THRESHOLD = 0.05
    CONF_LEVEL = 0.975
    SIGMA_M_LIST = [0.0, 0.1, 0.2]
    SIGMA_M = 0.1
    RISK_EARLY, RISK_MID, RISK_LATE = (1.0, 2.0, 4.0)
    RETEST_COST = 1.5
    VISIT_INTERVAL = 1.0
    FIRST_VISIT_COST = 0.0
    MAX_RETESTS = 10
    N_GROUPS = 4
    MIN_SEG_SIZE = 5
    EXTRAP_SIGMA_PER_WEEK = 0.45
    SOFT_BAND = 1.5
    SOFT_BETA = 4.0
    SOFT_POWER = 1.5
    T_MIN_RAW, T_MAX, STEP = (10.0, 30.0, 0.1)
    OUT_GROUP_SUMMARY = 'group_summary.csv'
    OUT_TSTAR_PNG = 't_star_vs_bmi.png'
    OUT_GROUPS_PNG = 'groups_on_curve.png'
    OUT_SENS_TG_PNG = 'sensitivity_Tg_sigma.png'
    WAIT_PENALTY_PER_WEEK = 1.0
